version: 2.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-github:
          context: deploy-public
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/go:1.14
    environment:
      CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name: "Compile Binary"
          command: |
            cd ./mdproofer
            if [ ! -z "$CIRCLE_TAG" ]; then
              go build -o md-proofer -ldflags "-X main.version=${CIRCLE_TAG}" .
            else
              go build -o md-proofer
            fi
      - run:
          name: "Run File Tests"
          command: |
            cd ./mdproofer
            if ./md-proofer lint ../good-test-files/; then
              echo "md-proofer passed the files. Continue on."
            else
              echo "The tests failed, which it shouldn't. Something is wrong."
              exit 1
            fi

            if ./md-proofer lint ../bad-test-files/; then
              echo "md-proofer returned an exit code of 0, which shouldn't be the case."
              exit 1
            else
              echo "The tests failed, which is what we expected. Continue on."
            fi

            if ./md-proofer lint ../good-test-files/ ../bad-test-files/; then
              echo "md-proofer returned an exit code of 0, which shouldn't be the case."
              exit 1
            else
              echo "Some of the tests failed, which is what we expected. Continue on."
            fi
      - run:
          name: "Prepare Binaries"
          command: |
            cd ./mdproofer
            mkdir binaries
            tar cfz ./binaries/md-proofer--${CIRCLE_TAG}--linux-amd64.tar.gz ./md-proofer
      - persist_to_workspace:
          root: .
          paths:
            - ./mdproofer/binaries

  publish-github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -prerelease $CIRCLE_TAG ./mdproofer/binaries/
